### ISSUE TITLE
一直找不到POP.h 另外cocoapods了进来也不行

### ISSUE THREAD

**Issue by apiapia** [LYM-mg/MGDYZB#1]
在bridge.h的文件里，要把POP.h的注释解开，就不行！
一直提示 'pop/POP.h' file not found或者 POP.h file not found ,
请问要如何解决这个问题?

 #ifndef Bridge_h
 #define Bridge_h

 #import "pop/POP.h"

 #endif /* Bridge_h */

#import "XRCarouselView.h"
#import "UIView+LYMExtension.h"
#import "DeformationButton.h"
#import "MJRefresh.h"
//#import "POP.h"   //MARK: - 一直找不到POP.h
//#import <POP.h>
//#import "MGTopWindow.h"

**Comment by LYM-mg** [comment]
![1](https://cloud.githubusercontent.com/assets/16550840/23329807/b367b2e2-fb7a-11e6-87e1-28113beef60c.png)
![2](https://cloud.githubusercontent.com/assets/16550840/23329808/b3f9c402-fb7a-11e6-8059-1aebf21a4c33.png)
![3](https://cloud.githubusercontent.com/assets/16550840/23329809/b47e9e2a-fb7a-11e6-8f9c-b3028c624afa.png)
![4](https://cloud.githubusercontent.com/assets/16550840/23329811/b665fe68-fb7a-11e6-8c74-80a13644505e.png)
下载别人的项目 框架啥的找不到，一般这样处理ok
